use ecommercedb;
#1.List all customers who have placed more than five orders in the past year.#

select c.customerid, c.firstname, c.lastname, ca.year, count(o.orderid) as Totalorders
from orders o 
inner join customers c
on o.customerid = c.customerid
inner join calendar ca
on ca.dateid = o.dateid
where year= 2024 
group by c.customerid
having count(o.orderid)> 5
order by customerid asc;

#2.List all customers who have placed more than five orders in the past year.#

select productname, stockQuantity
from products
order by stockQuantity asc;

select productname, stockQuantity
from products
where stockQuantity < 20
order by stockQuantity asc;

#3.Identify the top 5 best-selling products by total quantity sold#

select p.productname, p.productid, sum(od.quantity) as total_quantity_sold
from orderdetails od
inner join products p
	on p.productid = od.productid
inner join orders o
	on o.orderid = od.orderid
group by p.productid, p.productname
limit 5;

#4.Which customers have spent the most on orders this year?#

select c.firstname, c.lastname, sum(o.totalamount) as totalamountspent
from orders o 
inner join customers c
on o.customerid = c.customerid
group by  c.firstname, c.lastname
order by totalamountspent desc;

#5.What is the average order value per month, and how does it trend over the
year#

select ca.month, avg(o.totalamount) as average_value
from orders o
inner join calendar ca
on ca.dateid = o.dateid
group by ca.month
order by ca.month asc;

#6.Which product categories generate the highest revenue?#
select cat.categoryname, sum(unitprice*Quantity) as revenue
from categories cat
inner join products p
on p.categoryid = cat.categoryid
inner join orderdetails od
on od.productid = p.productid
group by cat.categoryname
order by revenue desc;

#7.Find the days of the week with the highest and lowest sales.#

select ca.dayofweek, sum(o.Totalamount) as Total_Sales_Amount
from calendar ca
inner join orders o
on o.dateid = ca.dateid
group by ca.dayofweek
order by Total_Sales_Amount desc;

#8.Which customers have not placed any orders in the last six months?#

SELECT c.CustomerID, c.FirstName, c.LastName
FROM Customers c
LEFT JOIN Orders o 
    ON c.CustomerID = o.CustomerID
LEFT JOIN Calendar ca 
    ON o.DateID = ca.DateID 
    AND ca.Date >= DATE_SUB('2024-12-31', INTERVAL 6 MONTH)
WHERE o.OrderID IS NULL;

#9.What is the total revenue generated by each product category last quarter?#

select cat.categoryid, cat.categoryname, sum(unitprice*quantity) as Total_Revenue
from categories cat
inner join products p
on p.CategoryID = cat.CategoryID
inner join orderdetails od
on od.productid = p.productid
inner join orders o
on o.orderid = od.orderid
inner join calendar ca
on ca.dateid = o.dateid
where ca.date >= '2024-01-01' and ca.date <= '2024-03-31'
group by cat.categoryid, cat.categoryname 
order by Total_Revenue desc;

#10.How many new customers were acquired each month?#

select ca.year, ca.month, count(distinct c.CustomerID) as New_Customers
from customers c
inner join orders o on c.CustomerID = o.CustomerID
inner join calendar ca on o.DateID = ca.DateID
inner join (
	select 
        o.customerID,
        min(ca.Date) as First_Order_Date
    from orders o
    inner join Calendar ca on o.DateID = ca.DateID
    group by o.CustomerID
) first_order on c.CustomerID = first_order.CustomerID 
    and ca.Date = first_order.First_Order_Date
group by ca.year, ca.month
order by ca.year, ca.month;

#11.Identify orders that include products from more than one category#

select o.orderid, count(distinct p.CategoryID) as Number_Of_Categories
from orders o
inner join orderdetails od
on od.orderid = o.OrderID
inner join products p
on p.productid = od.productid
group by o.orderid
having count(distinct p.CategoryID) > 1
order by Number_Of_Categories desc;


#12.Which products have never been sold?#

select p.productname, p.productid
from products p
inner join orderdetails od
on p.productid = od.productid
Where quantity is null;


#13.What is the average time between a customer’s orders?#

select FirstName, LastName, count(orderid) as Total_Orders, avg(Days_Between_Orders) as Days_Between_Orders
from(
	select FirstName, LastName, orderid, datediff(
    ca.date, lag(ca.date) over(partition by c.customerid order by ca.date)
    ) as Days_Between_Orders
    from customers c
    inner join orders o 
    on c.customerid = o.customerid
    inner join calendar ca
    on o.dateid = ca.dateid
    ) as order_intervals
where Days_Between_Orders is not null
group by FirstName, LastName
order by Days_Between_Orders desc;


#14.Which day of the month typically has the highest number of orders?#

Select ca.day as highest_day_of_the_month, count(o.orderid) as Total_Orders
from orders o
inner join calendar ca
on ca.dateid = o.dateid
group by ca.day
order by Total_Orders desc
limit 1;

#15.Create a view that summarizes total sales, number of orders, and average order value by customer.#

create view CustomerSalesSummary as
select c.customerid, c.firstname, c.lastname, count(distinct o.orderid) as Numbers_Of_Orders, sum(od.Quantity*od.Unitprice) as Total_Sales, avg(od.Quantity*od.Unitprice) as Average_Order_Value
from customers c
left join orders o
on o.customerid = c.customerid
left join orderdetails od
on od.OrderID = o.OrderID
group by c.customerid, c.firstname, c.lastname
order by Total_Sales desc;

#16.Create a view with the Customer payments#

create view Customer_Payments as
select c.customerid, c.firstname, c.lastname, ca.date as Order_Date, o.totalamount as Total_Payment_Amount, sum(od.Quantity*od.Unitprice) as Total_Sales
from customers c
inner join orders o
on c.customerid = o.customerid
inner join calendar ca
on ca.dateid = o.dateid
left join orderdetails od
on od.OrderID = o.orderid
group by c.customerid, c.firstname, c.lastname, ca.date, o.totalamount
order by Total_Sales desc;

#17.Create a view with the month sales#

create or replace view Month_Sales as
select ca.month, sum(od.Quantity*od.Unitprice) as Month_Sales
from orderdetails od
inner join orders o
on o.orderid = od.orderid
inner join calendar ca
on ca.dateid = o.dateid
group by ca.month
order by ca.month desc;

#18.Write a stored procedure to return all orders and order details for a given customer.#

Delimiter $$
create procedure Get_Customer_Orders_With_Summary (in customerid INT)
begin
	select c.customerid, contact(c.firstname, ' ', c.lastname) as Customer_Name, count(distinct o.orderid) as Total_Sales, sum(od.quantity*od.Unitprice) as Total_Spent
    from customer c
    left join orders o
    on o.customerid = c.customerid
    left join orderdetails od
    on od.orderid =o.orderid
    where c.customerid = customer_id
    group by c.customerid, c.firstname, c.lastname;
	select o.orderid, ca.date as Order_Date, p.productname, od.Quantity, od.unitprice, (od.quantity*od.Unitprice) as Total
    from customer c
    inner join orders o 
	on o.customerid = c.customerid    
    inner join calendar ca
    on ca.dateid = o.dateid
	inner join orderdetails od
    on od.orderid = o.orderid
    inner join products p
    on od.productid = p.productid
    where c.customerid = customer_id
    order by ca.date desc, o.orderid;
End$$
	Delimiter ;

#19.Procedure for the highest product sales#

Delimiter $$
create procedure Get_High_Product()
Begin
	select p.productid, p.productname,p.categoryid, sum(od.quantity) as Total_Quantity_Sold, sum(od.quantity*od.Unitprice) as Revenue, count(distinct od.orderid) as Number_Of_Orders, avg(od.Unitprice) as Average_Price
    from product p
    inner join orderdetials od
    on od.productid = p.productid
    group by p.productid, p.productname,p.categoryid
    order by Revenue desc;
End$$
Delimiter ;


#20.Which customers have returned for repeat purchases, and how many times?#

select c.customerid, c.firstname, c.lastname, count(o.orderid) as Total_Orders, min(ca.date) as First_Date_Of_Order, max(ca.date) as Last_Date_Of_Order, Datediff(max(ca.date), min(ca.date)) as Days_In_Between
from customers c
inner join orders o
on c.customerid = o.customerid
inner join calendar ca
on o.dateid = ca.dateid
group by c.customerid, c.firstname, c.lastname
having count(o.orderid) > 1
order by Total_Orders;

#21.What is the monthly sales growth rate over the past year?#

select year, month, Month_Name, Monthly_Sales, Previous_Month_Sales, Sales_Change, 
case
	when Previous_Month_Sales is null then null
    when Previous_Month_Sales = 0 then null
    else round((Sales_Change / Previous_Month_Sales)*100,2)
    End as Growth_Rate_Percent
from(
	select ca.year, ca.month, date_format(min(ca.date), '%M') as Month_Name,
    sum(od.Quantity*od.Unitprice) as Monthly_Sales,
    lag(sum(od.quantity*od.unitprice)) 
		over (order by ca.year, ca.month) as Previous_Month_Sales, 
	sum(od.quantity*od.unitprice) - lag(sum(od.quantity*od.unitprice)) over (order by ca.year, ca.month) as Sales_Change
from orders o
inner join orderdetails od 
on o.orderid = od.orderid
inner join calendar ca
on ca.dateid = o.dateid
group by ca.year, ca.month
)
as Monthly_Sales_Data
order by year, month;


#22.Identify the top 10 customers by total number of products purchased (not just order count).#

select c.customerid, c.firstname, c.lastname, sum(od.Quantity) as Total_Products, sum(od.Quantity*od.Unitprice) as Total_Spent, count(distinct od.orderid) as Total_Orders, count(distinct od.productid) as Total_Products, round(sum(od.quantity*od.unitprice)/ sum(od.quantity),2) as Average_Price_for_Product
from customers c
inner join orders o
on c.customerid = o.customerid
inner join orderdetails od
on  o.orderid = od.orderid
group by c.customerid, c.firstname, c.lastname
order by Total_Products
limit 10;

#23.For each month, what is the percentage of orders that included products from more than one category?#

with Order_Categories as (
    select 
        o.OrderID,
        o.DateID,
        count(distinct p.Categoryid) as Category_Count
    from Orders o
    inner join OrderDetails od 
    on o.OrderID = od.OrderID
	inner join Products p 
    on od.ProductID = p.ProductID
    group by o.OrderID, o.DateID
),
Monthly_Stats as (
    select
        cal.year,
        cal.month,
        date_format(min(cal.Date), '%M') as Month_Name,
        count(distinct oc.OrderID) as Total_Orders,
        sum(case when oc.Category_Count > 1 then 1 else 0 end) as Multi_Category_Orders,
        sum(case when oc.Category_Count = 1 then 1 else 0 end) as Single_Category_Orders
    from Order_Categories oc
    inner join Calendar cal 
    on oc.DateID = cal.DateID
    group by cal.year, cal.month
)
select year, month, Month_Name, Total_Orders, Multi_Category_Orders, Single_Category_Orders,
    round((Multi_Category_Orders / Total_Orders) * 100, 2) as Multi_Category_Percentage,
    round((Single_Category_Orders / Total_Orders) * 100, 2) as Single_Category_Percentage
from Monthly_Stats
order by year, month;